export const reducerCases = {
    ADD_TRACK : "ADD_TRACK",
    SET_PLAYING : "SET_PLAYING",
    NEXT_TRACK : "NEXT_TRACK",
    ADD_FAVORITES : "ADD_FAVORITES",
    REMOVE_FAVORITE : "REMOVE_FAVORITE"
    
}